[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2", features = ["derive"] }
command-ext = { git = "https://github.com/YdrMaster/command-ext.git", rev = "f25befb" }
log = "0.4.17"
once_cell = "1.13.0"
simplelog = "0.12.0"
common = { path = "../common" }
